### ISSUE TITLE
手机端无法显示文字

### ISSUE THREAD

**Issue by AnsonCode** [guyoung/streakjs#18]
您好，下载了咱们的源码，在电脑端可以预览，但手机端无法展示文字对象。

**Comment by AnsonCode** [comment]
![1](https://user-images.githubusercontent.com/20960032/95346226-2d4a1300-08ee-11eb-80e0-8c8e8b969ffc.jpg)

**Comment by guyoung** [comment]
调试状态，控制台有没有报错信息

**Comment by AnsonCode** [comment]
s手机端没有报错.
![b8fc7ef7cef970c12fdeefce65e19a3](https://user-images.githubusercontent.com/20960032/95415820-dc750180-0963-11eb-8f7c-aa8ab8f59b42.jpg)

**Comment by guyoung** [comment]
@caoyanbin1993 修改后的程序已解决文本无法显示问题

**Comment by AnsonCode** [comment]
感谢,已试用!
